project_name: Test
task_name: Eval MNIST
remote: True
queue_name: default
ignored_requirements:
  - pytorch_ignite
execution:
  model_conf:
    module: model
    name: MNISTEvalModel
    kwargs:
      id_: 178d786bba1c45aeab70c25a1f70a122
      batch_size: 64
  dataset_conf:
    module: dataset
    name: MNISTDataset
    kwargs:
      id_: 8a24087d9f6545c58bf98824ecc126e9
