project_name: Test
task_name: Eval MNIST
remote: True
queue_name: eval
ignored_requirements:
  - pytorch_ignite
execution:
  model_conf:
    module: model
    name: MNISTEvalModel
    kwargs:
      id_: 6e45951fd97f45069d4c59f6e2c6ebf6
      batch_size: 64
  dataset_conf:
    module: dataset
    name: MNISTDataset
    kwargs:
      id_: 583a8fff8f3b4307812eac1cfe00a5d9
