project_name: Test
task_name: Eval MNIST
execution:
  model_conf:
    module: examples.mnist.model
    name: MNISTEvalModel
    kwargs:
      id_: 19d348e5fd1b4048b252d90447bf04e6
      batch_size: 64
  dataset_conf:
    module: examples.mnist.dataset
    name: MNISTDataset
    kwargs:
      id_: 33e73c5ea5584cd69cd5504c7e33a8e6
