project_name: Test
task_name: Query random MNIST
remote: True
queue_name: query
ignored_requirements:
  - pytorch_ignite
execution:
  strategy: random
  n_samples: 1000
  data_source_conf:
    module: caml.data_source
    name: VisionX
    kwargs:
      task_ids:
        - 32782
