project_name: Test
task_name: Query random MNIST
execution:
  strategy: random
  n_samples: 1000
  data_source_conf:
    module: examples.mnist.data_source
    name: MNISTSource
    kwargs:
      split: test
