project_name: Test
task_name: Train MNIST
remote: True
queue_name: default
ignored_requirements:
  - pytorch_ignite
execution:
  model_conf:
    module: model
    name: MNISTTrainModel
    kwargs:
      num_epochs: 10
      batch_size: 64
  dataset_conf:
    module: dataset
    name: MNISTDataset
    kwargs:
      id_: 8a24087d9f6545c58bf98824ecc126e9
