project_name: Test
task_name: Train MNIST
execution:
  model_conf:
    module: examples.mnist.model
    name: MNISTTrainModel
    kwargs:
      num_epochs: 10
      batch_size: 64
  dataset_conf:
    module: examples.mnist.dataset
    name: MNISTDataset
    kwargs:
      id_: 619fb114238d4448a041a4665e0ff9ee
