project_name: Test
task_name: Train MNIST
remote: True
queue_name: train
ignored_requirements:
  - pytorch_ignite
execution:
  model_conf:
    module: model
    name: MNISTTrainModel
    kwargs:
      num_epochs: 10
      batch_size: 64
  dataset_conf:
    module: dataset
    name: MNISTDataset
    kwargs:
      id_: 583a8fff8f3b4307812eac1cfe00a5d9
