project_name: Test
task_name: Train MNIST
remote: True
queue_name: default
execution:
  model_conf:
    module: examples.mnist.model
    name: MNISTTrainModel
    kwargs:
      num_epochs: 10
      batch_size: 64
  dataset_conf:
    module: examples.mnist.dataset
    name: MNISTDataset
    kwargs:
      id_: 4b0ff23173154a69a63f05ffec83840a
