version: '3.9'
services:
  caml:
    build: .
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /workspace
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    extra_hosts:
      - host.docker.internal:host-gateway
